const uid = () => crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).slice(2);
const wait = ms => new Promise(r => setTimeout(r, ms));

function esc(s) {
  if (s === undefined || s === null) return '';
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

// â”€â”€ MERMAID DIAGRAM RENDERER â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
let mermaidLoaded = false;
let mermaidLoading = false;
let mermaidQueue = [];

async function loadMermaid() {
  if (mermaidLoaded) return Promise.resolve();
  if (mermaidLoading) return new Promise(r => mermaidQueue.push(r));
  mermaidLoading = true;
  return new Promise((resolve) => {
    const s = document.createElement('script');
    s.src = 'https://cdnjs.cloudflare.com/ajax/libs/mermaid/11.4.1/mermaid.min.js';
    s.onload = () => {
      window.mermaid?.initialize({
        startOnLoad: false, theme: 'dark',
        themeVariables: {
          primaryColor: '#00ff88', primaryTextColor: '#e8f5ec',
          primaryBorderColor: '#00ff88', lineColor: '#00cc6a',
          background: '#0d1410', mainBkg: '#151e18', nodeBorder: '#00ff88'
        }
      });
      mermaidLoaded = true; mermaidLoading = false;
      mermaidQueue.forEach(r => r()); mermaidQueue = [];
      resolve();
    };
    s.onerror = () => { mermaidLoading = false; resolve(); };
    document.head.appendChild(s);
  });
}

async function renderMermaidEl(el) {
  await loadMermaid();
  if (!window.mermaid) return;
  const id = 'mmd_' + Math.random().toString(36).slice(2);
  try {
    const { svg } = await window.mermaid.render(id, el.textContent.trim());
    const wrapper = document.createElement('div');
    wrapper.className = 'mermaid-diagram';
    // svg is generated by the trusted mermaid library, not user content
    wrapper.innerHTML = svg;
    el.replaceWith(wrapper);
  } catch (e) {
    el.classList.add('mermaid-error');
    el.title = 'Diagram parse error: ' + e.message;
  }
}

function md(text) {
  if (!text) return '';
  let hasMermaid = false;
  const result = text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/```mermaid\n?([\s\S]*?)```/gi, (_, code) => {
      hasMermaid = true;
      const id = 'mmd_pre_' + Math.random().toString(36).slice(2);
      // Mermaid code is rendered inside esc() via the original block, but we escaped everything at start.
      // Re-reversing the &lt; and &gt; for mermaid specifically so it can parse its syntax.
      const unescapedCode = code.trim().replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&amp;/g, '&');
      return `<pre class="mermaid-pre" id="${id}">${esc(unescapedCode)}</pre>`;
    })
    .replace(/```(\w*)\n?([\s\S]*?)```/g, (_, l, c) => {
      const unescapedCode = c.trim().replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&amp;/g, '&');
      return `<pre><code>${esc(unescapedCode)}</code></pre>`;
    })
    .replace(/`([^`\n]+)`/g, (_, c) => {
      const unescapedCode = c.replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&amp;/g, '&');
      return `<code>${esc(unescapedCode)}</code>`;
    })
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    .replace(/\*([^*\n]+)\*/g, '<em>$1</em>')
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    .replace(/^[-*] (.+)$/gm, '<li>$1</li>')
    .replace(/(<li>.*<\/li>)/gs, m => `<ul>${m}</ul>`)
    .replace(/\n{2,}/g, '</p><p>')
    .replace(/^([^<\n].+)$/gm, m => m.startsWith('<') ? m : `<p>${m}</p>`)
    .replace(/<p><\/p>/g, '')
    .replace(/\[(.*?)\]\((https?:\/\/.*?)\)/g, (_, label, url) => {
      const u = url.replace(/&amp;/g, '&');
      const safeUrl = u.replace(/"/g, '%22').replace(/'/g, '%27');
      return `<a href="${safeUrl}" target="_blank" rel="noopener noreferrer">${label}</a>`;
    })
    .replace(/(?<!href=")(https?:\/\/[^\s<"]+)/g, (_, url) => {
      const u = url.replace(/&amp;/g, '&');
      if (!/^https?:\/\//i.test(u)) return url;
      const safeUrl = u.replace(/"/g, '%22').replace(/'/g, '%27');
      return `<a href="${safeUrl}" target="_blank" rel="noopener noreferrer">${esc(u)}</a>`;
    });

  if (hasMermaid) {
    setTimeout(() => {
      document.querySelectorAll('.mermaid-pre').forEach(el => renderMermaidEl(el));
    }, 50);
  }
  return result;
}

function csvFromJSON(raw) {
  let rows;
  try { rows = typeof raw === 'string' ? JSON.parse(raw) : raw; } catch { rows = []; }
  if (!Array.isArray(rows) || !rows.length) return '';
  const data = Array.isArray(rows[0]) ? rows : (() => {
    const keys = Object.keys(rows[0]);
    return [keys, ...rows.map(r => keys.map(k => r[k]))];
  })();
  return data.map(r => r.map(c => {
    const s = String(c ?? '');
    return /[,"\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
  }).join(',')).join('\n');
}

// â”€â”€ STORAGE â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
